---
- name: Configure default PHPMyAdmin settings
  shell: 'echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections'

- name: Install PHPMyAdmin
  apt:
    name: phpmyadmin
    state: present

- name: Extract 'create_table' script
  command:
    'gunzip /usr/share/doc/phpmyadmin/examples/create_tables.sql.gz'
  args:
    creates: '/usr/share/doc/phpmyadmin/examples/create_tables.sql'

- name: Import phpmyadmin data
  mysql_db:
    login_host: '{{ phpmyadmin_host }}'
    login_user: '{{ phpmyadmin_user }}'
    login_password: '{{ phpmyadmin_pass }}'
    name: 'phpmyadmin'
    state: import
    target: '/usr/share/doc/phpmyadmin/examples/create_tables.sql'

- name: Include Debian Vars
  include_vars: Debian.yml
