---
- name: Install PyCurl
  yum:
    name: python-pycurl
    state: present

- name: Include RedHat Vars
  include_vars: RedHat.yml

- name: Add Jenkins Repository
  get_url:
    url: "http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo"
    dest: '/etc/yum.repos.d/jenkins.repo'

- name: Add Jenkins Repository Key
  rpm_key:
    key: "https://jenkins-ci.org/redhat/jenkins-ci.org.key"
    state: present

- name: Install Java
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - 'java-1.7.0-openjdk'

- name: Install Jenkins
  yum:
    name: jenkins
    state: present
